# Generated by Django 4.0.2 on 2022-06-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_boleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
